### ISSUE TITLE
NumPy Monte Carlo

### ISSUE THREAD

**Issue by kimjoyc** [msse-2021-bootcamp/team1-project#24]
NumPy Monte Carlo
Take an hour or so to discuss with your teammates what changes you can make to your code to take advantage of the features of NumPy arrays. For this portion, take the first 30 minutes to think about this by yourself, then discuss for half an hour with your group. We will tell you one option for rewriting your code at the end of this discussion period.

Consider each function in our code - which ones could benefit from using numpy arrays? Consider each function and include thoughts for each one in your blog post for today.

**Comment by annamarieweber** [comment]
resolved by #30
